default:
  image: python:3.7

stages:
  - build
  - test
  - publish
  - deploy

tags:
  - bvm15 # Use our Drexel machine

mlflow-server:build:
  stage: build
  only:
    changes:
      - images/mlflow.Dockerfile
    script: docker build -t mlflow-server:$CI_COMMIT_REF_SLUG -f ./images/mlflow.Dockerfile ./images

mlflow-server:publish:
  stage: publish
  only:
    refs:
      - master
    changes:
      - images/mlflow.Dockerfile
  script: docker tag mlflow-server:$CI_COMMIT_REF_SLUG mlflow-server:latest


experiments:build:
  stage: build
  only:
    changes:
      - images/experiments.Dockerfile
      - src/python/experiment_platform/*
    script: docker build -t experiments:$CI_COMMIT_REF_SLUG -f ./images/experiments.Dockerfile ./src/python

    
experiments:publish:
  stage: publish
  only:
    refs:
      - master
    changes:
      - images/experiments.Dockerfile
      - src/python/experiment_platform/*
    script: docker tag experiments:$CI_COMMIT_REF_SLUG experiments:latest

deploy:
  stage: deploy
  only:
    changes:
      - images/*
      - src/python/experiment_platform/*
  script: docker-compose up -d